plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ffoptimizer'
    compileSdk 36

    defaultConfig {
        applicationId 'com.ffoptimizer'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildFeatures {
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.17.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'com.google.android.material:material:1.14.0'

    implementation 'dev.rikka.shizuku:api:12.2.0'
    implementation 'dev.rikka.shizuku:provider:12.2.0'
}
